# Generated by Django 4.0.2 on 2022-05-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_userplant_custom_name_userplant_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='matched_plant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='matched_plant', to='main_app.plant'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='user_plant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userplant', to='main_app.plant'),
        ),
    ]
