# Generated by Django 4.0.2 on 2022-05-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=100)),
                ('plant', models.CharField(max_length=100)),
                ('plant_match', models.ManyToManyField(to='main_app.Plant')),
            ],
        ),
    ]
