# Generated by Django 4.0.2 on 2022-05-24 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_userplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplant',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='plant_match',
        ),
        migrations.AddField(
            model_name='photo',
            name='data',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='userplant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
