# Generated by Django 4.0.2 on 2022-05-24 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_plant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplant',
            name='custom_name',
        ),
        migrations.AddField(
            model_name='userplant',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='userplant',
            name='user_plant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.plant'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
