# Generated by Django 4.0.2 on 2022-05-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_userplant_plant_remove_userplant_plant_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='data',
        ),
    ]
