# Generated by Django 4.0.2 on 2022-05-24 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_photo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='plant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.plant'),
        ),
    ]
