# Generated by Django 4.0.2 on 2022-05-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userplant_matched_plant_alter_userplant_user_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='user_plant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_plant', to='main_app.plant'),
        ),
    ]
