# Generated by Django 4.0.2 on 2022-05-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.plant'),
        ),
    ]
